// ── WIZARD STEP DEFINITIONS ─────────────────────────────────────────────
export const PHASES = [
  {id:1,en:"About You",       es:"Sobre Ti",          fr:"À Propos de Vous",      col:"#3b82f6"},
  {id:2,en:"Your Family",     es:"Tu Familia",         fr:"Votre Famille",          col:"#8b5cf6"},
  {id:3,en:"Your Background", es:"Tu Historial",       fr:"Votre Passé",            col:"#f59e0b"},
  {id:4,en:"Your Journey",    es:"Tu Viaje a Canadá",  fr:"Votre Voyage au Canada", col:"#06b6d4"},
  {id:5,en:"PRRA History",    es:"Historial PRRA",     fr:"Historique PRRA",        col:"#10b981"},
  {id:6,en:"Your Story",      es:"Tu Historia",        fr:"Votre Histoire",         col:"#ef4444"},
  {id:7,en:"Documents",       es:"Documentos",         fr:"Documents",              col:"#6366f1"},
];

export const STATUS_OPTS = [
  {v:"citizen",  en:"Citizen",             es:"Ciudadano/a",          fr:"Citoyen(ne)"},
  {v:"resident", en:"Permanent resident",  es:"Residente permanente", fr:"Résident(e) permanent(e)"},
  {v:"tourist",  en:"Tourist / visitor",   es:"Turista / visitante",  fr:"Touriste / visiteur(se)"},
  {v:"student",  en:"Student",             es:"Estudiante",           fr:"Étudiant(e)"},
  {v:"worker",   en:"Work permit",         es:"Permiso de trabajo",   fr:"Permis de travail"},
  {v:"transit",  en:"In transit",          es:"En tránsito",          fr:"En transit"},
  {v:"illegal",  en:"Without legal status",es:"Sin estatus legal",    fr:"Sans statut légal"},
  {v:"other",    en:"Other",               es:"Otro",                 fr:"Autre"},
];

export const TRANSPORT_OPTS = [
  {v:"plane",e:"✈️",en:"Airplane",    es:"Avión",         fr:"Avion"},
  {v:"bus",  e:"🚌",en:"Bus",         es:"Autobús",       fr:"Autobus"},
  {v:"car",  e:"🚗",en:"Car / truck", es:"Carro / camión",fr:"Voiture / camion"},
  {v:"train",e:"🚂",en:"Train",       es:"Tren",          fr:"Train"},
  {v:"boat", e:"🚢",en:"Boat / ship", es:"Barco",         fr:"Bateau"},
  {v:"walk", e:"🚶",en:"On foot",     es:"A pie",         fr:"À pied"},
  {v:"other",e:"🔄",en:"Other",       es:"Otro",          fr:"Autre"},
];

export const DOC_TYPE_OPTS = [
  {v:"passport",  en:"Passport",             es:"Pasaporte",               fr:"Passeport"},
  {v:"travel",    en:"Travel document",       es:"Documento de viaje",      fr:"Document de voyage"},
  {v:"id",        en:"National ID card",      es:"Cédula de identidad",     fr:"Carte d'identité nationale"},
  {v:"visa",      en:"Visa",                  es:"Visa",                    fr:"Visa"},
  {v:"birth",     en:"Birth certificate",     es:"Acta de nacimiento",      fr:"Acte de naissance"},
  {v:"drivers",   en:"Driver's license",      es:"Licencia de conducir",    fr:"Permis de conduire"},
  {v:"education", en:"Education certificate", es:"Certificado de educación",fr:"Certificat d'études"},
  {v:"military",  en:"Military document",     es:"Documento militar",       fr:"Document militaire"},
  {v:"other",     en:"Other document",        es:"Otro documento",          fr:"Autre document"},
];

export const MARITAL_OPTS = [
  {v:"unmarried", e:"🙋",en:"Unmarried (never married)",  es:"Soltero/a",             fr:"Célibataire"},
  {v:"married",   e:"💍",en:"Married",                    es:"Casado/a",              fr:"Marié(e)"},
  {v:"commonlaw", e:"🤝",en:"Common-law partner",         es:"Pareja de hecho",       fr:"Conjoint(e) de fait"},
  {v:"widowed",   e:"🕊️",en:"Widowed",                   es:"Viudo/a",               fr:"Veuf/veuve"},
  {v:"separated", e:"↔️",en:"Legally separated",          es:"Separado/a legalmente", fr:"Séparé(e) légalement"},
  {v:"divorced",  e:"📋",en:"Divorced",                   es:"Divorciado/a",          fr:"Divorcé(e)"},
  {v:"annulled",  e:"🚫",en:"Annulled",                   es:"Anulado/a",             fr:"Annulé(e)"},
];

export const EYE_OPTS = [
  {v:"brown",en:"Brown", es:"Café",     fr:"Brun"},
  {v:"black",en:"Black", es:"Negro",    fr:"Noir"},
  {v:"blue", en:"Blue",  es:"Azul",     fr:"Bleu"},
  {v:"green",en:"Green", es:"Verde",    fr:"Vert"},
  {v:"hazel",en:"Hazel", es:"Avellana", fr:"Noisette"},
  {v:"grey", en:"Grey",  es:"Gris",     fr:"Gris"},
  {v:"other",en:"Other", es:"Otro",     fr:"Autre"},
];

export const GOV_POSITIONS = [
  {en:"Head of state or government",                              es:"Jefe/a de estado o gobierno",                          fr:"Chef d'État ou de gouvernement"},
  {en:"Member of cabinet or governing council",                   es:"Miembro del gabinete o consejo de gobierno",           fr:"Membre du cabinet ou conseil de gouvernement"},
  {en:"Senior advisor to head of state or cabinet",               es:"Asesor/a senior del jefe de estado o gabinete",        fr:"Conseiller(ère) principal(e) du chef d'État"},
  {en:"Senior member of the public service",                      es:"Miembro senior del servicio público",                  fr:"Membre supérieur(e) de la fonction publique"},
  {en:"Senior military, intelligence or security member",         es:"Miembro senior de militares, inteligencia o seguridad",fr:"Membre supérieur(e) de l'armée ou du renseignement"},
  {en:"Ambassador or senior diplomatic official",                 es:"Embajador/a o funcionario diplomático de alto rango",  fr:"Ambassadeur(drice) ou haut(e) fonctionnaire diplomatique"},
  {en:"Member of the judiciary (judge or prosecutor)",            es:"Miembro del poder judicial (juez/a o fiscal)",         fr:"Membre du pouvoir judiciaire (juge ou procureur)"},
];

export const STEPS = [

// PRE-PHASE: INTERPRETER
{id:"interpreter",phase:0,field:"needsInterpreter",type:"choice",
  en:{q:"If there is an interview, will you need an interpreter?",intro:"Some people prefer to speak in their own language during immigration interviews. There is no wrong answer."},
  es:{q:"Si hay una entrevista, ¿necesitarás un intérprete?"},
  fr:{q:"Si une entrevue est requise, aurez-vous besoin d'un interprète?"},
  opts:[
    {v:"no",  e:"✅",en:"No — I am comfortable in English or French",es:"No — me siento cómodo/a en inglés o francés",fr:"Non — je suis à l'aise en anglais ou français"},
    {v:"yes", e:"🗣️",en:"Yes — I need an interpreter",               es:"Sí — necesito un intérprete",              fr:"Oui — j'ai besoin d'un interprète"},
  ],
},
{id:"interpreterLang",phase:0,field:"interpreterLanguage",type:"text",when:a=>a.needsInterpreter==="yes",
  en:{q:"What language does the interpreter need to speak?",ph:"e.g. Spanish, Arabic, Somali"},
  es:{q:"¿Qué idioma debe hablar el intérprete?",ph:"ej. Español, Árabe, Somalí"},
  fr:{q:"Quelle langue l'interprète doit-il parler?",ph:"ex. Espagnol, Arabe, Somali"},
},

// PHASE 1
{id:"firstName",phase:1,field:"firstName",type:"text",
  en:{q:"What is your first name?",intro:"Welcome. We are here to help you prepare your PRRA application step by step. Let us start with your name.",ph:"Your first name"},
  es:{q:"¿Cuál es tu nombre?",intro:"Bienvenido/a. Estamos aquí para ayudarte a preparar tu solicitud PRRA paso a paso.",ph:"Tu nombre"},
  fr:{q:"Quel est votre prénom?",intro:"Bienvenue. Nous sommes ici pour vous aider à préparer votre demande PRRA étape par étape.",ph:"Votre prénom"},
},
{id:"lastName",phase:1,field:"lastName",type:"text",
  en:{q:"And your last name?",ph:"Your last name / family name"},
  es:{q:"¿Y tu apellido?",ph:"Tu apellido"},
  fr:{q:"Et votre nom de famille?",ph:"Votre nom de famille"},
},
{id:"otherNames",phase:1,field:"otherNames",type:"textSkip",
  en:{q:"Have you used any other names — maiden name, nickname, or alias?",ph:"e.g. Maria Rodriguez (maiden name) — or skip"},
  es:{q:"¿Has usado algún otro nombre — nombre de soltera, apodo o alias?",ph:"ej. María Rodríguez — o saltar"},
  fr:{q:"Avez-vous déjà utilisé d'autres noms — nom de jeune fille, surnom ou alias?",ph:"ex. Maria Rodriguez — ou ignorer"},
},
{id:"sex",phase:1,field:"sex",type:"choice",
  en:{q:"What is your sex?"},es:{q:"¿Cuál es tu sexo?"},fr:{q:"Quel est votre sexe?"},
  opts:[
    {v:"male",  e:"👨",en:"Male",  es:"Masculino",fr:"Masculin"},
    {v:"female",e:"👩",en:"Female",es:"Femenino", fr:"Féminin"},
  ],
},
{id:"dob",phase:1,field:"dob",type:"date",
  en:{q:"What is your date of birth?",intro:"Use the date on your official documents like your passport or birth certificate."},
  es:{q:"¿Cuál es tu fecha de nacimiento?",intro:"Usa la fecha en tus documentos oficiales."},
  fr:{q:"Quelle est votre date de naissance?",intro:"Utilisez la date figurant sur vos documents officiels."},
},
{id:"placeOfBirth",phase:1,field:"placeOfBirth",type:"text",
  en:{q:"Where were you born?",intro:"Write the city and the country where you were born.",ph:"City and country — e.g. Caracas, Venezuela"},
  es:{q:"¿Dónde naciste?",ph:"Ciudad y país — ej. Caracas, Venezuela"},
  fr:{q:"Où êtes-vous né(e)?",ph:"Ville et pays — ex. Caracas, Venezuela"},
},
{id:"country",phase:1,field:"country",type:"text",
  en:{q:"What country are you a citizen of?",intro:"This is the country that issued your passport, or where you hold citizenship.",ph:"e.g. Venezuela, Ethiopia, Colombia"},
  es:{q:"¿De qué país eres ciudadano/a?",ph:"ej. Venezuela, Etiopía, Colombia"},
  fr:{q:"De quel pays êtes-vous citoyen(ne)?",ph:"ex. Venezuela, Éthiopie, Colombie"},
},
{id:"citizenship2",phase:1,field:"citizenship2",type:"textSkip",
  en:{q:"Are you also a citizen of any other country?",intro:"Some people hold citizenship in more than one country. If you only have one, tap Skip.",ph:"Second country of citizenship — or skip"},
  es:{q:"¿Eres también ciudadano/a de algún otro país?",ph:"Segundo país de ciudadanía — o saltar"},
  fr:{q:"Êtes-vous également citoyen(ne) d'un autre pays?",ph:"Deuxième pays de citoyenneté — ou ignorer"},
},
{id:"physicalDesc",phase:1,field:"physicalDesc",type:"grouped",
  en:{q:"We need a brief physical description for the official form.",intro:"Height, weight, and eye color — for identification purposes only."},
  es:{q:"Necesitamos una breve descripción física para el formulario oficial.",intro:"Estatura, peso y color de ojos — solo para identificación."},
  fr:{q:"Nous avons besoin d'une brève description physique pour le formulaire officiel.",intro:"Taille, poids et couleur des yeux — à des fins d'identification uniquement."},
  subFields:[
    {id:"height",  en:{label:"Height",ph:"e.g. 165 cm"},es:{label:"Estatura"},fr:{label:"Taille"}},
    {id:"weight",  en:{label:"Weight",ph:"e.g. 65 kg"},es:{label:"Peso"},fr:{label:"Poids"}},
    {id:"eyeColor",en:{label:"Eye color"},es:{label:"Color de ojos"},fr:{label:"Couleur des yeux"},type:"select",opts:EYE_OPTS},
  ],
},
{id:"maritalStatus",phase:1,field:"maritalStatus",type:"choice",
  en:{q:"What is your current marital status?"},
  es:{q:"¿Cuál es tu estado civil actual?"},
  fr:{q:"Quel est votre état civil actuel?"},
  opts:MARITAL_OPTS,
},
{id:"address",phase:1,field:"address",type:"text",
  en:{q:"What is your current address in Canada?",intro:"Write your complete address — street number, street name, city, and province.",ph:"e.g. 123 Main Street, Toronto, Ontario"},
  es:{q:"¿Cuál es tu dirección actual en Canadá?",ph:"ej. 123 Main Street, Toronto, Ontario"},
  fr:{q:"Quelle est votre adresse actuelle au Canada?",ph:"ex. 123 rue Principale, Toronto, Ontario"},
},
{id:"postalCode",phase:1,field:"postalCode",type:"text",
  en:{q:"What is your postal code?",ph:"e.g. M5V 2T6"},
  es:{q:"¿Cuál es tu código postal?",ph:"ej. M5V 2T6"},
  fr:{q:"Quel est votre code postal?",ph:"ex. M5V 2T6"},
},
{id:"homePhone",phase:1,field:"homePhone",type:"text",
  en:{q:"What is your home telephone number?",intro:"Include your area code. Immigration Canada may call you at this number.",ph:"e.g. 416-555-1234"},
  es:{q:"¿Cuál es tu número de teléfono en casa?",ph:"ej. 416-555-1234"},
  fr:{q:"Quel est votre numéro de téléphone à domicile?",ph:"ex. 416-555-1234"},
},
{id:"msgPhone",phase:1,field:"msgPhone",type:"textSkip",
  en:{q:"Is there another phone number where people can leave you a message?",ph:"Message phone number — or skip"},
  es:{q:"¿Hay otro número donde puedan dejarte un mensaje?",ph:"Número para mensajes — o saltar"},
  fr:{q:"Y a-t-il un autre numéro où l'on peut vous laisser un message?",ph:"Numéro pour messages — ou ignorer"},
},
{id:"callTime",phase:1,field:"callTime",type:"text",
  en:{q:"What is the best time of day to reach you by phone?",intro:"Immigration Canada will try to call you at this time.",ph:"e.g. 9:00 AM, 2:30 PM"},
  es:{q:"¿Cuál es la mejor hora del día para contactarte?",ph:"ej. 9:00 AM, 2:30 PM"},
  fr:{q:"Quelle est la meilleure heure pour vous joindre?",ph:"ex. 9h00, 14h30"},
},
{id:"notificationMethod",phase:1,field:"notificationMethod",type:"choice",
  en:{q:"How did you receive your PRRA notification?",intro:"This determines exactly how many days you have. Missing the deadline means immediate deportation."},
  es:{q:"¿Cómo recibiste tu notificación PRRA?",intro:"Esto determina exactamente cuántos días tienes. Perderte la fecha límite significa deportación inmediata."},
  fr:{q:"Comment avez-vous reçu votre notification PRRA?",intro:"Cela détermine exactement combien de jours vous avez. Manquer la date limite signifie une déportation immédiate."},
  opts:[
    {v:"inperson",e:"🏢",en:"In person from a CBSA officer — 15 days to apply",  es:"En persona de un oficial de la CBSA — 15 días para aplicar",fr:"En personne d'un agent de l'ASFC — 15 jours pour postuler"},
    {v:"mail",    e:"📬",en:"By mail — 22 days to apply",                        es:"Por correo postal — 22 días para aplicar",                  fr:"Par courrier postal — 22 jours pour postuler"},
  ],
},
{id:"notificationDate",phase:1,field:"notificationDate",type:"date",
  en:{q:"What date did you receive the notification?",intro:"We will calculate your exact deadline and show it throughout the entire process."},
  es:{q:"¿Qué fecha recibiste la notificación?",intro:"Calcularemos tu fecha límite exacta y la mostraremos durante todo el proceso."},
  fr:{q:"À quelle date avez-vous reçu la notification?",intro:"Nous calculerons votre date limite exacte et l'afficherons tout au long du processus."},
},
{id:"isFirstPRRA",phase:1,field:"isFirstPRRA",type:"choice",
  en:{q:"Is this your first PRRA application in Canada?",intro:"Do not worry — either answer is fine. We just need to know your history."},
  es:{q:"¿Es esta tu primera solicitud PRRA en Canadá?",intro:"No te preocupes — cualquier respuesta está bien."},
  fr:{q:"Est-ce votre première demande PRRA au Canada?",intro:"Ne vous inquiétez pas — les deux réponses sont valides."},
  opts:[
    {v:"yes",e:"✅",en:"Yes — this is my first PRRA",   es:"Sí — es mi primer PRRA",       fr:"Oui — c'est mon premier PRRA"},
    {v:"no", e:"🔄",en:"No — I have had a PRRA before", es:"No — ya tuve un PRRA antes",   fr:"Non — j'ai déjà eu un PRRA"},
  ],
},

// PHASE 2
{id:"familyInCanada",phase:2,field:"familyInCanada",type:"choice",
  en:{q:"Is anyone else applying for a PRRA with you at the same time?",intro:"This would be your spouse or children also in Canada who received a PRRA notification. Each adult (18+) needs their own separate form."},
  es:{q:"¿Hay alguien más solicitando un PRRA contigo al mismo tiempo?",intro:"Esto sería tu cónyuge o hijos también en Canadá que recibieron una notificación PRRA. Cada adulto (18+) necesita su propio formulario."},
  fr:{q:"Y a-t-il quelqu'un d'autre qui fait une demande PRRA en même temps que vous?",intro:"Ce serait votre conjoint(e) ou vos enfants au Canada qui ont aussi reçu une notification PRRA. Chaque adulte (18+) doit remplir son propre formulaire."},
  opts:[
    {v:"no", e:"👤",en:"No — I am applying alone",                  es:"No — aplico solo/a",             fr:"Non — je postule seul(e)"},
    {v:"yes",e:"👨‍👩‍👧",en:"Yes — family members are applying with me",es:"Sí — familiares aplican conmigo",fr:"Oui — des membres de ma famille postulent avec moi"},
  ],
},
{id:"familyApplying",phase:2,field:"familyApplying",type:"repeat",when:a=>a.familyInCanada==="yes",
  max:3,min:1,
  en:{q:"Tell us about each family member applying with you.",intro:"Add each person one at a time. The form allows up to 3 here — if you have more, we will note that.",addBtn:"Add a family member",doneBtn:"I have added everyone applying with me"},
  es:{q:"Cuéntanos sobre cada familiar que aplica contigo.",intro:"Agrega cada persona una por una.",addBtn:"Agregar un familiar",doneBtn:"Ya agregué a todos los que aplican conmigo"},
  fr:{q:"Parlez-nous de chaque membre de la famille qui postule avec vous.",intro:"Ajoutez chaque personne une par une.",addBtn:"Ajouter un membre de la famille",doneBtn:"J'ai ajouté tout le monde"},
  subFields:[
    {id:"surname",     req:true,en:{label:"Last name"},                                        es:{label:"Apellido"},         fr:{label:"Nom de famille"}},
    {id:"givenNames",  req:true,en:{label:"First name(s)"},                                    es:{label:"Nombre(s)"},        fr:{label:"Prénom(s)"}},
    {id:"sex",         req:true,en:{label:"Sex"},es:{label:"Sexo"},fr:{label:"Sexe"},type:"select",opts:[{v:"male",en:"Male",es:"Masculino",fr:"Masculin"},{v:"female",en:"Female",es:"Femenino",fr:"Féminin"}]},
    {id:"dob",         req:true,en:{label:"Date of birth (YYYY-MM-DD)"},                      es:{label:"Fecha de nacimiento"},fr:{label:"Date de naissance"}},
    {id:"marital",     req:true,en:{label:"Marital status"},es:{label:"Estado civil"},fr:{label:"État civil"},type:"select",opts:MARITAL_OPTS},
    {id:"relationship",req:true,en:{label:"Relationship to you",ph:"e.g. Spouse, Son, Daughter"},es:{label:"Relación contigo"},fr:{label:"Lien de parenté"}},
    {id:"clientId",         en:{label:"UCI / Client ID (if known)",ph:"Leave blank if unknown"},es:{label:"UCI / ID de Cliente (si se conoce)"},fr:{label:"IUC / ID client (si connu)"}},
    {id:"citizenship", req:true,en:{label:"Country of citizenship"},                           es:{label:"País de ciudadanía"},fr:{label:"Pays de citoyenneté"}},
  ],
},
{id:"familyWorldwide",phase:2,field:"familyWorldwide",type:"repeat",
  max:13,
  en:{q:"Tell us about your close family members anywhere in the world.",intro:"Include your spouse or partner, all children, parents, grandparents, brothers and sisters — wherever they live. Add one at a time. If you have no close family to list, tap Skip.",addBtn:"Add a family member",doneBtn:"I have added all my family members",skipBtn:"Skip — no family members to add"},
  es:{q:"Cuéntanos sobre tus familiares cercanos en cualquier parte del mundo.",intro:"Incluye tu cónyuge o pareja, todos tus hijos, padres, abuelos, hermanos y hermanas — donde sea que vivan.",addBtn:"Agregar un familiar",doneBtn:"Ya agregué a todos mis familiares",skipBtn:"Saltar — no hay familiares que agregar"},
  fr:{q:"Parlez-nous de vos proches partout dans le monde.",intro:"Incluez votre conjoint(e) ou partenaire, tous vos enfants, parents, grands-parents, frères et sœurs — où qu'ils vivent.",addBtn:"Ajouter un proche",doneBtn:"J'ai ajouté tous mes proches",skipBtn:"Ignorer — aucun proche à ajouter"},
  subFields:[
    {id:"familyName",   req:true,en:{label:"Last name"},es:{label:"Apellido"},fr:{label:"Nom de famille"}},
    {id:"givenName",    req:true,en:{label:"First name"},es:{label:"Nombre"},fr:{label:"Prénom"}},
    {id:"dob",          req:true,en:{label:"Date of birth (YYYY-MM-DD)"},es:{label:"Fecha de nacimiento"},fr:{label:"Date de naissance"}},
    {id:"citizenship",  req:true,en:{label:"Country of citizenship"},es:{label:"País de ciudadanía"},fr:{label:"Pays de citoyenneté"}},
    {id:"relationship", req:true,en:{label:"Relationship to you",ph:"e.g. Mother, Father, Brother"},es:{label:"Relación contigo"},fr:{label:"Lien de parenté"}},
    {id:"inCanada",     req:true,en:{label:"Are they in Canada?"},es:{label:"¿Están en Canadá?"},fr:{label:"Sont-ils au Canada?"},type:"select",opts:[{v:"yes",en:"Yes — in Canada",es:"Sí — en Canadá",fr:"Oui — au Canada"},{v:"no",en:"No — living abroad",es:"No — viven en el exterior",fr:"Non — vivant à l'étranger"},{v:"deceased",en:"Deceased",es:"Fallecido/a",fr:"Décédé(e)"}]},
    {id:"statusOrLocation",req:true,en:{label:"If in Canada: immigration status. If abroad: where they live. If deceased: date of death.",ph:"e.g. Permanent Resident / Caracas, Venezuela / Jan 2020"},es:{label:"Si en Canadá: estatus. Si en el exterior: dónde vive. Si fallecido/a: fecha."},fr:{label:"Si au Canada: statut. Si à l'étranger: où ils habitent. Si décédé(e): date."}},
  ],
},

// PHASE 3
{id:"countriesLived",phase:3,field:"countriesLived",type:"repeat",
  max:4,
  en:{q:"In the past 10 years, did you live in any country besides your home country and Canada?",intro:"Your home country is already included automatically. Only add countries where you actually lived — not just passed through.",addBtn:"Add a country I lived in",doneBtn:"I have added all countries",skipBtn:"No — I came directly from my home country"},
  es:{q:"En los últimos 10 años, ¿viviste en algún país además de tu país de origen y Canadá?",intro:"Tu país de origen ya está incluido automáticamente.",addBtn:"Agregar un país donde viví",doneBtn:"Ya agregué todos los países",skipBtn:"No — vine directamente de mi país de origen"},
  fr:{q:"Au cours des 10 dernières années, avez-vous vécu dans un autre pays que votre pays d'origine et le Canada?",intro:"Votre pays d'origine est déjà inclus automatiquement.",addBtn:"Ajouter un pays où j'ai vécu",doneBtn:"J'ai ajouté tous les pays",skipBtn:"Non — je suis venu(e) directement de mon pays d'origine"},
  subFields:[
    {id:"country",  req:true,en:{label:"Country"},es:{label:"País"},fr:{label:"Pays"}},
    {id:"status",   req:true,en:{label:"Your status there"},es:{label:"Tu estatus ahí"},fr:{label:"Votre statut là-bas"},type:"select",opts:STATUS_OPTS},
    {id:"dateFrom", req:true,en:{label:"From (month/year)",ph:"e.g. 03/2020"},es:{label:"Desde"},fr:{label:"De"}},
    {id:"dateTo",   req:true,en:{label:"To (month/year)",ph:"e.g. 11/2022"},  es:{label:"Hasta"},fr:{label:"À"}},
  ],
},
{id:"beenToCanada",phase:3,field:"beenToCanada",type:"choice",
  en:{q:"Before this time, had you ever been to Canada?"},
  es:{q:"Antes de esta vez, ¿habías estado en Canadá?"},
  fr:{q:"Avant cette fois-ci, aviez-vous déjà été au Canada?"},
  opts:[
    {v:"yes",e:"✅",en:"Yes — I have been to Canada before",  es:"Sí — ya había estado en Canadá",   fr:"Oui — j'ai déjà été au Canada"},
    {v:"no", e:"❌",en:"No — this is my first time in Canada",es:"No — es mi primera vez en Canadá", fr:"Non — c'est ma première fois au Canada"},
  ],
},
{id:"canadaVisits",phase:3,field:"canadaVisits",type:"repeat",when:a=>a.beenToCanada==="yes",
  max:3,
  en:{q:"Tell us about your previous visits to Canada.",intro:"List up to 3 visits, most recent first.",addBtn:"Add a visit",doneBtn:"I have added all my previous visits"},
  es:{q:"Cuéntanos sobre tus visitas anteriores a Canadá.",intro:"Lista hasta 3 visitas, empezando por la más reciente.",addBtn:"Agregar una visita",doneBtn:"Ya agregué todas mis visitas"},
  fr:{q:"Parlez-nous de vos visites précédentes au Canada.",intro:"Listez jusqu'à 3 visites, en commençant par la plus récente.",addBtn:"Ajouter une visite",doneBtn:"J'ai ajouté toutes mes visites"},
  subFields:[
    {id:"dateFrom",req:true,en:{label:"From (month/year)",ph:"e.g. 06/2019"},es:{label:"Desde"},fr:{label:"De"}},
    {id:"dateTo",  req:true,en:{label:"To (month/year)",ph:"e.g. 09/2019"},  es:{label:"Hasta"},fr:{label:"À"}},
    {id:"purpose", req:true,en:{label:"Purpose of visit",ph:"e.g. Tourism, Work, Family visit"},es:{label:"Motivo de la visita"},fr:{label:"Motif de la visite"}},
  ],
},
{id:"warCrimes",phase:3,field:"warCrimes",type:"choice",
  en:{q:"During a war or conflict, were you ever involved in actions that caused serious harm to civilians or prisoners?",intro:"This is a required question on the form. It refers to things like killings, torture, or forced displacement. Be honest — context matters. If you were a victim or forced, that is important information."},
  es:{q:"Durante una guerra o conflicto, ¿alguna vez participaste en acciones que causaron daño grave a civiles o prisioneros?",intro:"Esta es una pregunta requerida en el formulario."},
  fr:{q:"Lors d'une guerre ou d'un conflit, avez-vous déjà participé à des actions ayant causé de graves préjudices à des civils ou des prisonniers?",intro:"C'est une question obligatoire sur le formulaire."},
  opts:[
    {v:"no", e:"✅",en:"No",                                      es:"No",                               fr:"Non"},
    {v:"yes",e:"⚠️",en:"Yes — I was involved in such actions",   es:"Sí — participé en tales acciones", fr:"Oui — j'ai participé à de telles actions"},
  ],
},
{id:"militaryService",phase:3,field:"militaryService",type:"choice",
  en:{q:"Have you ever served in the military, army, police, or any armed or paramilitary group?",intro:"This includes any country, any time in your life."},
  es:{q:"¿Alguna vez has servido en el ejército, fuerzas armadas, policía, o cualquier grupo armado o paramilitar?",intro:"Esto incluye cualquier país, en cualquier momento de tu vida."},
  fr:{q:"Avez-vous déjà servi dans l'armée, la police ou un groupe armé ou paramilitaire?",intro:"Cela inclut tout pays, à tout moment de votre vie."},
  opts:[
    {v:"no", e:"✅",en:"No",                                              es:"No",                                        fr:"Non"},
    {v:"yes",e:"🪖",en:"Yes — I served in military or armed forces",     es:"Sí — serví en fuerzas militares o armadas", fr:"Oui — j'ai servi dans les forces armées"},
  ],
},
{id:"militaryDetails",phase:3,field:"militaryDetails",type:"repeat",when:a=>a.militaryService==="yes",
  max:3,
  en:{q:"Tell us about your military or armed service.",addBtn:"Add a service period",doneBtn:"I have added all service periods"},
  es:{q:"Cuéntanos sobre tu servicio militar o armado.",addBtn:"Agregar un período de servicio",doneBtn:"Ya agregué todos los períodos"},
  fr:{q:"Parlez-nous de votre service militaire ou armé.",addBtn:"Ajouter une période de service",doneBtn:"J'ai ajouté toutes les périodes"},
  subFields:[
    {id:"dateFrom",  req:true,en:{label:"From (month/year)"},es:{label:"Desde"},fr:{label:"De"}},
    {id:"dateTo",    req:true,en:{label:"To (month/year)"},  es:{label:"Hasta"},fr:{label:"À"}},
    {id:"orgName",   req:true,en:{label:"Name of military or organization",ph:"e.g. Venezuelan Army"},es:{label:"Nombre de la organización"},fr:{label:"Nom de l'organisation"}},
    {id:"location",  req:true,en:{label:"Where did you serve?",ph:"Country or region"},es:{label:"¿Dónde serviste?"},fr:{label:"Où avez-vous servi?"}},
    {id:"position",  req:true,en:{label:"Your rank or position",ph:"e.g. Private, Officer, Guard"},es:{label:"Tu rango o posición"},fr:{label:"Votre grade ou poste"}},
  ],
},
{id:"armedConflict",phase:3,field:"armedConflict",type:"choice",
  en:{q:"Have you ever been personally involved in an armed conflict or war?",intro:"Even as a civilian caught in fighting. This is different from military service."},
  es:{q:"¿Alguna vez has estado personalmente involucrado/a en un conflicto armado o guerra?",intro:"Incluso como civil atrapado/a en los combates."},
  fr:{q:"Avez-vous déjà été personnellement impliqué(e) dans un conflit armé ou une guerre?",intro:"Même en tant que civil(e) pris(e) dans des combats."},
  opts:[
    {v:"no", e:"✅",en:"No",                                    es:"No",                                  fr:"Non"},
    {v:"yes",e:"⚠️",en:"Yes — I was involved in armed conflict",es:"Sí — estuve en un conflicto armado", fr:"Oui — j'ai été impliqué(e) dans un conflit armé"},
  ],
},
{id:"conflictDetails",phase:3,field:"conflictDetails",type:"repeat",when:a=>a.armedConflict==="yes",
  max:3,
  en:{q:"Tell us about the armed conflict.",addBtn:"Add a conflict",doneBtn:"I have added all conflicts"},
  es:{q:"Cuéntanos sobre el conflicto armado.",addBtn:"Agregar un conflicto",doneBtn:"Ya agregué todos"},
  fr:{q:"Parlez-nous du conflit armé.",addBtn:"Ajouter un conflit",doneBtn:"J'ai ajouté tous les conflits"},
  subFields:[
    {id:"dateFrom", req:true,en:{label:"From (month/year)"},es:{label:"Desde"},fr:{label:"De"}},
    {id:"dateTo",   req:true,en:{label:"To (month/year)"},  es:{label:"Hasta"},fr:{label:"À"}},
    {id:"location", req:true,en:{label:"Where?",ph:"Country, region, or city"},es:{label:"¿Dónde?"},fr:{label:"Où?"}},
    {id:"role",     req:true,en:{label:"Briefly describe your role or involvement",ph:"e.g. I was a civilian caught in fighting / I was forced to join / I helped protect civilians"},es:{label:"Describe brevemente tu papel"},fr:{label:"Décrivez brièvement votre rôle"}},
  ],
},
{id:"govPositions",phase:3,field:"govPositions",type:"multiChoice",
  en:{q:"Have you ever held any of these positions in the service of any government?",intro:"Check any that apply — any country, any time in your life."},
  es:{q:"¿Has ocupado alguna vez alguno de estos puestos al servicio de algún gobierno?",intro:"Marca los que apliquen — cualquier país, en cualquier momento de tu vida."},
  fr:{q:"Avez-vous déjà occupé l'un de ces postes au service d'un gouvernement?",intro:"Cochez tout ce qui s'applique — n'importe quel pays, à tout moment de votre vie."},
  opts:GOV_POSITIONS.map((p,i)=>({v:String(i+1),e:"🏛️",...p})),
  noneOpt:{en:"None of these — I have never held a government position",es:"Ninguno — nunca ocupé un cargo gubernamental",fr:"Aucun — jamais occupé un poste gouvernemental"},
},
{id:"govPositionDetails",phase:3,field:"govPositionDetails",type:"textarea",when:a=>Array.isArray(a.govPositions)&&a.govPositions.length>0,
  en:{q:"Please describe your work, duties, and responsibilities in those positions.",intro:"Include the organization name, your title, dates, and what you actually did.",ph:"Describe your government positions, duties and responsibilities in detail…"},
  es:{q:"Describe tu trabajo, funciones y responsabilidades en esos cargos.",ph:"Describe tus cargos gubernamentales, funciones y responsabilidades en detalle…"},
  fr:{q:"Décrivez votre travail, vos fonctions et responsabilités dans ces postes.",ph:"Décrivez vos postes gouvernementaux, fonctions et responsabilités en détail…"},
},
{id:"criminalRecord",phase:3,field:"criminalRecord",type:"choice",
  en:{q:"Have you ever been charged with or convicted of any crime — in Canada or any other country?",intro:"We need to ask this because it affects which type of PRRA you qualify for. There is no judgment here. Your answer is private and stored only in your browser."},
  es:{q:"¿Alguna vez te han acusado o condenado por algún delito — en Canadá o en cualquier otro país?",intro:"Necesitamos preguntar esto porque afecta el tipo de PRRA al que tienes derecho. No hay juicio. Tu respuesta es privada."},
  fr:{q:"Avez-vous déjà été accusé(e) ou reconnu(e) coupable d'un crime — au Canada ou dans un autre pays?",intro:"Nous devons poser cette question car cela affecte le type de PRRA. Il n'y a aucun jugement. Votre réponse est privée."},
  opts:[
    {v:"none",   e:"✅",en:"No — I have no criminal record",                        es:"No — no tengo antecedentes penales",                fr:"Non — je n'ai pas de casier judiciaire"},
    {v:"minor",  e:"⚠️",en:"A minor offence (small fine or misdemeanor)",           es:"Un delito menor (multa pequeña o infracción)",      fr:"Une infraction mineure (petite amende ou contravention)"},
    {v:"serious",e:"🔴",en:"A serious crime (sentenced 2+ years, or 10+ year max)", es:"Un delito grave (condena 2+ años, o pena máx 10+)", fr:"Un crime grave (condamné 2+ ans, ou passible de 10+)"},
    {v:"unsure", e:"❓",en:"I am not sure",                                         es:"No estoy seguro/a",                                 fr:"Je ne suis pas sûr(e)"},
  ],
},
{id:"criminalCharges",phase:3,field:"criminalCharges",type:"repeat",when:a=>a.criminalRecord!=="none"&&a.criminalRecord!==undefined,
  max:5,
  en:{q:"Tell us about the charge or conviction.",intro:"Add each charge or conviction separately.",addBtn:"Add a charge or conviction",doneBtn:"I have added all charges"},
  es:{q:"Cuéntanos sobre el cargo o condena.",addBtn:"Agregar un cargo o condena",doneBtn:"Ya agregué todos los cargos"},
  fr:{q:"Parlez-nous de l'accusation ou de la condamnation.",addBtn:"Ajouter une accusation",doneBtn:"J'ai ajouté toutes les accusations"},
  subFields:[
    {id:"charge",   req:true,en:{label:"What was the charge or conviction?",ph:"e.g. Theft, Assault"},es:{label:"¿Cuál fue el cargo?"},fr:{label:"Quelle était l'accusation?"}},
    {id:"date",     req:true,en:{label:"Date (day/month/year)",ph:"e.g. 15/03/2018"},es:{label:"Fecha"},fr:{label:"Date"}},
    {id:"where",    req:true,en:{label:"Where? (city and country)",ph:"e.g. Bogotá, Colombia"},es:{label:"¿Dónde? (ciudad y país)"},fr:{label:"Où? (ville et pays)"}},
    {id:"sentence", req:true,en:{label:"Sentence or outcome",ph:"e.g. 6 months, Fine of $500, Charges dropped"},es:{label:"Sentencia o resultado"},fr:{label:"Peine ou résultat"}},
  ],
},
{id:"criminalCircumstances",phase:3,field:"criminalCircumstances",type:"textarea",when:a=>a.criminalRecord!=="none"&&a.criminalRecord!==undefined,
  en:{q:"Describe the circumstances around these charges or convictions.",intro:"Tell us what happened and why. You can explain if you were forced, falsely accused, or any other important context.",ph:"Describe the circumstances surrounding the charges or convictions…"},
  es:{q:"Describe las circunstancias alrededor de estos cargos o condenas.",ph:"Describe las circunstancias que rodearon los cargos o condenas…"},
  fr:{q:"Décrivez les circonstances entourant ces accusations ou condamnations.",ph:"Décrivez les circonstances entourant les accusations ou condamnations…"},
},
{id:"claimRejected",phase:3,field:"claimRejected",type:"choice",
  en:{q:"Was your refugee claim previously rejected by a Canadian immigration judge?",intro:"If yes, there is an important legal rule: you can ONLY use NEW evidence — evidence that did not exist before or that you could not access before."},
  es:{q:"¿Tu solicitud de refugio fue rechazada por un juez de inmigración canadiense?",intro:"Si sí, hay una regla legal importante: SOLO puedes usar evidencia NUEVA."},
  fr:{q:"Votre demande d'asile a-t-elle été rejetée par un juge de l'immigration canadienne?",intro:"Si oui, il existe une règle légale importante: vous ne pouvez utiliser que des preuves NOUVELLES."},
  opts:[
    {v:"yes",   e:"❌",en:"Yes — it was rejected",            es:"Sí — fue rechazada",          fr:"Oui — elle a été rejetée"},
    {v:"no",    e:"✅",en:"No — I never had a refugee claim", es:"No — nunca tuve solicitud",   fr:"Non — je n'ai jamais eu de demande"},
    {v:"unsure",e:"❓",en:"I am not sure",                    es:"No estoy seguro/a",            fr:"Je ne suis pas sûr(e)"},
  ],
},
{id:"uci",phase:3,field:"uci",type:"textSkip",
  en:{q:"Do you have a UCI / Client ID number from Immigration Canada?",intro:"Your UCI is on any letter from IRCC or CBSA. It looks like: 1234-5678. If you do not have it right now, tap Skip.",ph:"Enter your UCI — e.g. 1234-5678"},
  es:{q:"¿Tienes un número de UCI / ID de Cliente de Inmigración Canadá?",intro:"Tu UCI está en cualquier carta del IRCC o la CBSA. Se ve así: 1234-5678. Si no lo tienes, toca Saltar.",ph:"Escribe tu UCI — ej. 1234-5678"},
  fr:{q:"Avez-vous un numéro IUC / ID client d'Immigration Canada?",intro:"Votre IUC figure sur toute lettre de l'IRCC ou de l'ASFC. Il ressemble à: 1234-5678. Si vous ne l'avez pas, appuyez sur Ignorer.",ph:"Entrez votre IUC — ex. 1234-5678"},
},

// PHASE 4
{id:"arrivalInCanada",phase:4,field:"arrivalInCanada",type:"grouped",
  en:{q:"When and where did you arrive in Canada?",intro:"We need the exact date and the place where you entered Canada — airport, border crossing, or other point."},
  es:{q:"¿Cuándo y dónde llegaste a Canadá?",intro:"Necesitamos la fecha exacta y el lugar donde entraste a Canadá."},
  fr:{q:"Quand et où êtes-vous arrivé(e) au Canada?",intro:"Nous avons besoin de la date exacte et du lieu où vous êtes entré(e) au Canada."},
  subFields:[
    {id:"arrivalDate",  req:true,type:"date",en:{label:"Date of arrival in Canada"},es:{label:"Fecha de llegada a Canadá"},fr:{label:"Date d'arrivée au Canada"}},
    {id:"arrivalPlace", req:true,en:{label:"Place of arrival (airport, border crossing, province)",ph:"e.g. Pearson Airport, Toronto, Ontario"},es:{label:"Lugar de llegada"},fr:{label:"Lieu d'arrivée"}},
  ],
},
{id:"journeyRoute",phase:4,field:"journeyRoute",type:"repeat",
  max:5,min:1,
  en:{q:"Tell us about your journey to Canada — every country you passed through.",intro:"Start with your home country. Add each stop along the way, ending with Canada. Tell us how you traveled, what company or airline, and the dates.",addBtn:"Add a country I passed through",doneBtn:"I have completed my full journey route"},
  es:{q:"Cuéntanos sobre tu viaje a Canadá — cada país por el que pasaste.",intro:"Comienza con tu país de origen. Agrega cada parada en el camino, terminando con Canadá.",addBtn:"Agregar un país por el que pasé",doneBtn:"Ya completé toda mi ruta de viaje"},
  fr:{q:"Parlez-nous de votre voyage vers le Canada — chaque pays par lequel vous êtes passé(e).",intro:"Commencez par votre pays d'origine. Ajoutez chaque étape, en terminant par le Canada.",addBtn:"Ajouter un pays par lequel je suis passé(e)",doneBtn:"J'ai complété mon itinéraire complet"},
  subFields:[
    {id:"country",    req:true,en:{label:"Country"},es:{label:"País"},fr:{label:"Pays"}},
    {id:"status",     req:true,en:{label:"Your status in this country"},es:{label:"Tu estatus en este país"},fr:{label:"Votre statut dans ce pays"},type:"select",opts:STATUS_OPTS},
    {id:"transport",  req:true,en:{label:"How did you travel from here?"},es:{label:"¿Cómo viajaste desde aquí?"},fr:{label:"Comment avez-vous voyagé depuis ici?"},type:"select",opts:TRANSPORT_OPTS},
    {id:"company",         en:{label:"Airline or company name (if known)",ph:"e.g. Air France, Greyhound"},es:{label:"Aerolínea o empresa (si se conoce)"},fr:{label:"Compagnie (si connue)"}},
    {id:"arrivalDate",req:true,en:{label:"Date arrived in this country",ph:"e.g. 15/01/2024"},es:{label:"Fecha de llegada a este país"},fr:{label:"Date d'arrivée dans ce pays"}},
    {id:"departDate", req:true,en:{label:"Date left this country",ph:"e.g. 20/02/2024"},       es:{label:"Fecha de salida de este país"},fr:{label:"Date de départ de ce pays"}},
  ],
},
{id:"arrivalStatus",phase:4,field:"arrivalStatus",type:"multiChoice",
  en:{q:"When you arrived in Canada, what was your situation?",intro:"Select everything that applies. There is no wrong answer — be honest. Immigration officers understand that people fleeing danger sometimes have no choice."},
  es:{q:"Cuando llegaste a Canadá, ¿cuál era tu situación?",intro:"Selecciona todo lo que aplica. No hay respuesta incorrecta — sé honesto/a."},
  fr:{q:"Quand vous êtes arrivé(e) au Canada, quelle était votre situation?",intro:"Sélectionnez tout ce qui s'applique. Il n'y a pas de mauvaise réponse — soyez honnête(e)."},
  opts:[
    {v:"lawful",    e:"✅",en:"I was lawfully admitted as a temporary resident (student visa, work permit, etc.)",es:"Fui admitido/a legalmente como residente temporal",fr:"J'ai été admis(e) légalement comme résident(e) temporaire"},
    {v:"terpermit", e:"📋",en:"I had a temporary resident permit",                                               es:"Tenía un permiso de residente temporal",          fr:"J'avais un permis de séjour temporaire"},
    {v:"falsedocs", e:"⚠️",en:"I used unofficial or false documents, or did not declare all facts",              es:"Usé documentos no oficiales o falsos, o no declaré todos los hechos",fr:"J'ai utilisé des documents non officiels ou faux"},
  ],
  noneOpt:{en:"None of these apply",es:"Ninguno de estos aplica",fr:"Aucun de ces éléments ne s'applique"},
},
{id:"falseDocsDetail",phase:4,field:"falseDocsDetail",type:"textarea",when:a=>Array.isArray(a.arrivalStatus)&&a.arrivalStatus.includes("falsedocs"),
  en:{q:"Tell us more about the documents or circumstances at your arrival.",intro:"Explain what happened — what documents were used, were they false, and where are they now? You can be completely honest here.",ph:"Describe the documents used or facts not declared, and where those documents are now…"},
  es:{q:"Cuéntanos más sobre los documentos o las circunstancias de tu llegada.",ph:"Describe los documentos usados o los hechos no declarados, y dónde están esos documentos ahora…"},
  fr:{q:"Dites-nous en plus sur les documents ou les circonstances à votre arrivée.",ph:"Décrivez les documents utilisés ou les faits non déclarés, et où se trouvent ces documents maintenant…"},
},
{id:"arrivalDocs",phase:4,field:"arrivalDocs",type:"repeat",
  max:3,
  en:{q:"What documents did you show when you arrived at the Canadian border?",intro:"Add each document separately.",addBtn:"Add a document I showed at the border",doneBtn:"I have added all documents I showed"},
  es:{q:"¿Qué documentos mostraste cuando llegaste a la frontera canadiense?",addBtn:"Agregar un documento que mostré",doneBtn:"Ya agregué todos los documentos"},
  fr:{q:"Quels documents avez-vous présentés à la frontière canadienne?",addBtn:"Ajouter un document présenté",doneBtn:"J'ai ajouté tous les documents présentés"},
  subFields:[
    {id:"type",       req:true,en:{label:"Type of document"},es:{label:"Tipo de documento"},fr:{label:"Type de document"},type:"select",opts:DOC_TYPE_OPTS},
    {id:"country",    req:true,en:{label:"Country that issued it"},es:{label:"País que lo emitió"},fr:{label:"Pays qui l'a émis"}},
    {id:"issueDate",        en:{label:"Date issued (if known)",ph:"e.g. 10/2019"},es:{label:"Fecha de emisión (si se conoce)"},fr:{label:"Date d'émission (si connue)"}},
    {id:"expiryDate",       en:{label:"Date of expiry (if known)"},es:{label:"Fecha de vencimiento (si se conoce)"},fr:{label:"Date d'expiration (si connue)"}},
    {id:"serialNum",        en:{label:"Document number (if known)"},es:{label:"Número del documento (si se conoce)"},fr:{label:"Numéro de document (si connu)"}},
  ],
},
{id:"passportApplied",phase:4,field:"passportApplied",type:"choice",
  en:{q:"Did you apply for a passport or travel document to leave your home country?"},
  es:{q:"¿Solicitaste un pasaporte o documento de viaje para salir de tu país?"},
  fr:{q:"Avez-vous demandé un passeport ou un document de voyage pour quitter votre pays?"},
  opts:[
    {v:"yes",e:"✅",en:"Yes — I applied",    es:"Sí — solicité",    fr:"Oui — j'ai demandé"},
    {v:"no", e:"❌",en:"No — I did not apply",es:"No — no solicité", fr:"Non — je n'ai pas demandé"},
  ],
},
{id:"passportIssued",phase:4,field:"passportIssued",type:"choice",when:a=>a.passportApplied==="yes",
  en:{q:"Were you issued that passport or travel document?"},
  es:{q:"¿Te emitieron ese pasaporte o documento de viaje?"},
  fr:{q:"Ce passeport ou document de voyage vous a-t-il été délivré?"},
  opts:[
    {v:"yes",e:"✅",en:"Yes — I received it",        es:"Sí — lo recibí",       fr:"Oui — je l'ai reçu"},
    {v:"no", e:"❌",en:"No — it was not given to me",es:"No — no me lo dieron", fr:"Non — il ne m'a pas été remis"},
  ],
},
{id:"exitVisaNeeded",phase:4,field:"exitVisaNeeded",type:"choice",
  en:{q:"Did you need an exit visa or permit to leave your home country?",intro:"Some countries require official permission to leave."},
  es:{q:"¿Necesitabas una visa de salida o permiso para salir de tu país?",intro:"Algunos países requieren permiso oficial para salir."},
  fr:{q:"Aviez-vous besoin d'un visa ou permis de sortie pour quitter votre pays?",intro:"Certains pays exigent une autorisation officielle pour partir."},
  opts:[
    {v:"yes",e:"✅",en:"Yes — my country required an exit visa or permit",es:"Sí — mi país requería visa o permiso de salida",fr:"Oui — mon pays exigeait un visa ou permis de sortie"},
    {v:"no", e:"❌",en:"No — my country did not require one",             es:"No — mi país no requería uno",               fr:"Non — mon pays n'en exigeait pas"},
  ],
},
{id:"exitVisaApplied",phase:4,field:"exitVisaApplied",type:"choice",when:a=>a.exitVisaNeeded==="yes",
  en:{q:"Did you apply for the exit visa or permit?"},
  es:{q:"¿Solicitaste la visa o permiso de salida?"},
  fr:{q:"Avez-vous demandé le visa ou le permis de sortie?"},
  opts:[
    {v:"yes",e:"✅",en:"Yes — I applied",    es:"Sí — solicité",    fr:"Oui — j'ai demandé"},
    {v:"no", e:"❌",en:"No — I did not apply",es:"No — no solicité", fr:"Non — je n'ai pas demandé"},
  ],
},
{id:"exitVisaIssued",phase:4,field:"exitVisaIssued",type:"choice",when:a=>a.exitVisaApplied==="yes",
  en:{q:"Were you issued the exit visa or permit?"},
  es:{q:"¿Te emitieron la visa o permiso de salida?"},
  fr:{q:"Le visa ou permis de sortie vous a-t-il été délivré?"},
  opts:[
    {v:"yes",e:"✅",en:"Yes — it was issued",      es:"Sí — me lo emitieron",  fr:"Oui — il a été délivré"},
    {v:"no", e:"❌",en:"No — it was not issued",   es:"No — no me lo emitieron",fr:"Non — il ne m'a pas été remis"},
  ],
},
{id:"whyNoDocApplied",phase:4,field:"whyNoDocApplied",type:"textarea",
  when:a=>a.passportApplied==="no"||a.exitVisaApplied==="no",
  en:{q:"Why did you not apply for the passport or exit document?",intro:"Be honest — many people cannot apply because doing so would put them in danger.",ph:"e.g. I was afraid applying would alert the authorities persecuting me / I had to leave urgently and secretly / Applying was too dangerous…"},
  es:{q:"¿Por qué no solicitaste el pasaporte o documento de salida?",ph:"ej. Tenía miedo de que solicitar alertara a las autoridades / Tuve que salir urgente y secretamente…"},
  fr:{q:"Pourquoi n'avez-vous pas demandé le passeport ou le document de sortie?",ph:"ex. J'avais peur que ma demande alerte les autorités / J'ai dû partir d'urgence et secrètement…"},
},
{id:"whyDocsNotIssued",phase:4,field:"whyDocsNotIssued",type:"textarea",
  when:a=>a.passportIssued==="no"||a.exitVisaIssued==="no",
  en:{q:"Why were the documents not issued to you?",intro:"Explain what reason you were given, or why you believe they refused.",ph:"e.g. I was told my file was under review / The authorities refused without giving a reason / I believe I was denied because of my political opinion…"},
  es:{q:"¿Por qué no te emitieron los documentos?",ph:"ej. Me dijeron que mi expediente estaba bajo revisión / Las autoridades se negaron sin dar razón…"},
  fr:{q:"Pourquoi les documents ne vous ont-ils pas été délivrés?",ph:"ex. On m'a dit que mon dossier était en cours d'examen / Les autorités ont refusé sans donner de raison…"},
},
{id:"issuedDocs",phase:4,field:"issuedDocs",type:"repeat",
  when:a=>a.passportIssued==="yes"||a.exitVisaIssued==="yes",
  max:3,
  en:{q:"Tell us about the documents that were officially issued to you.",intro:"Include any passport, visa, or travel document officially given to you. Note if any were false or not in your real name.",addBtn:"Add an issued document",doneBtn:"I have added all issued documents"},
  es:{q:"Cuéntanos sobre los documentos que te emitieron oficialmente.",addBtn:"Agregar un documento emitido",doneBtn:"Ya agregué todos los documentos emitidos"},
  fr:{q:"Parlez-nous des documents qui vous ont été officiellement délivrés.",addBtn:"Ajouter un document délivré",doneBtn:"J'ai ajouté tous les documents délivrés"},
  subFields:[
    {id:"type",      req:true,en:{label:"Type of document"},es:{label:"Tipo de documento"},fr:{label:"Type de document"},type:"select",opts:DOC_TYPE_OPTS},
    {id:"number",         en:{label:"Document number (if known)"},es:{label:"Número del documento (si se conoce)"},fr:{label:"Numéro de document (si connu)"}},
    {id:"country",   req:true,en:{label:"Country of issue"},es:{label:"País de emisión"},fr:{label:"Pays d'émission"}},
    {id:"issueDate",      en:{label:"Date issued"},es:{label:"Fecha de emisión"},fr:{label:"Date d'émission"}},
    {id:"expiryDate",     en:{label:"Date of expiry"},es:{label:"Fecha de vencimiento"},fr:{label:"Date d'expiration"}},
    {id:"whereNow",  req:true,en:{label:"Where is this document now?",ph:"e.g. Surrendered to CBSA / Still in my possession / Lost"},es:{label:"¿Dónde está este documento ahora?"},fr:{label:"Où se trouve ce document maintenant?"}},
    {id:"isfalse",   req:true,en:{label:"Was this document false or not in your real name?"},es:{label:"¿Era falso o no estaba a tu nombre real?"},fr:{label:"Ce document était-il faux ou pas à votre vrai nom?"},type:"select",opts:[{v:"no",en:"No — genuine and in my name",es:"No — genuino y a mi nombre",fr:"Non — authentique et à mon nom"},{v:"yes",en:"Yes — false or in another name",es:"Sí — falso o con otro nombre",fr:"Oui — faux ou sous un autre nom"}]},
  ],
},
{id:"otherTravelDocs",phase:4,field:"otherTravelDocs",type:"repeat",
  max:4,
  en:{q:"Did you use any other documents to travel — including unofficial or false ones not yet mentioned?",addBtn:"Add another travel document",doneBtn:"I have no more travel documents to add",skipBtn:"No other travel documents to add"},
  es:{q:"¿Usaste algún otro documento para viajar — incluyendo no oficiales o falsos que aún no hayas mencionado?",addBtn:"Agregar otro documento de viaje",doneBtn:"Ya no tengo más documentos que agregar",skipBtn:"No hay más documentos de viaje que agregar"},
  fr:{q:"Avez-vous utilisé d'autres documents pour voyager — y compris des documents non officiels ou faux non encore mentionnés?",addBtn:"Ajouter un autre document de voyage",doneBtn:"Je n'ai plus de documents à ajouter",skipBtn:"Aucun autre document de voyage à ajouter"},
  subFields:[
    {id:"type",    req:true,en:{label:"Type of document"},es:{label:"Tipo de documento"},fr:{label:"Type de document"},type:"select",opts:DOC_TYPE_OPTS},
    {id:"number",       en:{label:"Document number"},es:{label:"Número"},fr:{label:"Numéro"}},
    {id:"country", req:true,en:{label:"Country of issue"},es:{label:"País de emisión"},fr:{label:"Pays d'émission"}},
    {id:"issueDate",    en:{label:"Date issued"},es:{label:"Fecha de emisión"},fr:{label:"Date d'émission"}},
    {id:"isfalse", req:true,en:{label:"Was this false or not in your real name?"},es:{label:"¿Era falso o no estaba a tu nombre?"},fr:{label:"Était-il faux ou pas à votre nom?"},type:"select",opts:[{v:"no",en:"No — genuine and in my name",es:"No — genuino y a mi nombre",fr:"Non — authentique et à mon nom"},{v:"yes",en:"Yes — false or in another name",es:"Sí — falso o con otro nombre",fr:"Oui — faux ou sous un autre nom"}]},
  ],
},
{id:"docsInPossession",phase:4,field:"docsInPossession",type:"repeat",
  max:4,
  en:{q:"What travel and identity documents do you have with you right now in Canada?",intro:"List every official document you currently have — passport, birth certificate, driver's license, diploma, anything. You need to include copies with your application.",addBtn:"Add a document I have",doneBtn:"I have listed all my documents"},
  es:{q:"¿Qué documentos de viaje e identidad tienes contigo ahora en Canadá?",intro:"Lista cada documento oficial que tienes actualmente. Necesitas incluir copias con tu solicitud.",addBtn:"Agregar un documento que tengo",doneBtn:"Ya listé todos mis documentos"},
  fr:{q:"Quels documents de voyage et d'identité avez-vous en votre possession au Canada?",intro:"Listez chaque document officiel que vous possédez actuellement. Vous devez inclure des copies avec votre demande.",addBtn:"Ajouter un document que j'ai",doneBtn:"J'ai listé tous mes documents"},
  subFields:[
    {id:"type",    req:true,en:{label:"Type of document"},es:{label:"Tipo de documento"},fr:{label:"Type de document"},type:"select",opts:DOC_TYPE_OPTS},
    {id:"number",       en:{label:"Document number (if known)"},es:{label:"Número del documento (si se conoce)"},fr:{label:"Numéro de document (si connu)"}},
    {id:"country", req:true,en:{label:"Country of issue"},es:{label:"País de emisión"},fr:{label:"Pays d'émission"}},
    {id:"issueDate",    en:{label:"Date issued"},es:{label:"Fecha de emisión"},fr:{label:"Date d'émission"}},
  ],
},
{id:"appliedDocsAfterArrival",phase:4,field:"appliedDocsAfterArrival",type:"choice",
  en:{q:"Since arriving in Canada, have you applied for or renewed any travel document?",intro:"For example, renewing a passport, or applying for a national ID from any country."},
  es:{q:"Desde que llegaste a Canadá, ¿has solicitado o renovado algún documento de viaje?",intro:"Por ejemplo, renovar un pasaporte o solicitar una cédula de algún país."},
  fr:{q:"Depuis votre arrivée au Canada, avez-vous demandé ou renouvelé un document de voyage?",intro:"Par exemple, renouveler un passeport ou demander une pièce d'identité."},
  opts:[
    {v:"yes",e:"✅",en:"Yes — I applied for or renewed a document",      es:"Sí — solicité o renovié un documento",        fr:"Oui — j'ai demandé ou renouvelé un document"},
    {v:"no", e:"❌",en:"No — I have not applied for any new documents",  es:"No — no he solicitado nuevos documentos",     fr:"Non — je n'ai pas demandé de nouveaux documents"},
  ],
},
{id:"appliedDocsDetails",phase:4,field:"appliedDocsDetails",type:"repeat",when:a=>a.appliedDocsAfterArrival==="yes",
  max:2,
  en:{q:"Tell us about the documents you applied for after arrival.",addBtn:"Add a document",doneBtn:"I have added all"},
  es:{q:"Cuéntanos sobre los documentos que solicitaste después de llegar.",addBtn:"Agregar",doneBtn:"Ya agregué todos"},
  fr:{q:"Parlez-nous des documents demandés après votre arrivée.",addBtn:"Ajouter",doneBtn:"J'ai tout ajouté"},
  subFields:[
    {id:"type",    req:true,en:{label:"Type of document"},es:{label:"Tipo"},fr:{label:"Type"},type:"select",opts:DOC_TYPE_OPTS},
    {id:"number",       en:{label:"Document number (if issued)"},es:{label:"Número (si fue emitido)"},fr:{label:"Numéro (si délivré)"}},
    {id:"country", req:true,en:{label:"Country of issue"},es:{label:"País de emisión"},fr:{label:"Pays d'émission"}},
    {id:"appDate", req:true,en:{label:"Date of application",ph:"e.g. 03/2024"},es:{label:"Fecha de solicitud"},fr:{label:"Date de la demande"}},
  ],
},
{id:"travelLast5Years",phase:4,field:"travelLast5Years",type:"choice",
  en:{q:"In the 5 years before coming to Canada, did you travel to any country other than your home country?",intro:"Any trips at all — for work, family, vacation, or any reason."},
  es:{q:"En los 5 años antes de venir a Canadá, ¿viajaste a algún país que no fuera tu país de origen?",intro:"Cualquier viaje — por trabajo, familia, vacaciones, o cualquier razón."},
  fr:{q:"Dans les 5 années avant de venir au Canada, avez-vous voyagé dans un autre pays que votre pays d'origine?",intro:"Tout voyage — pour le travail, la famille, des vacances, ou toute autre raison."},
  opts:[
    {v:"yes",e:"✅",en:"Yes — I traveled to other countries",    es:"Sí — viajé a otros países",          fr:"Oui — j'ai voyagé dans d'autres pays"},
    {v:"no", e:"❌",en:"No — I stayed in my home country only", es:"No — me quedé en mi país de origen", fr:"Non — je suis resté(e) dans mon pays d'origine"},
  ],
},
{id:"travelLast5Details",phase:4,field:"travelLast5Details",type:"textarea",when:a=>a.travelLast5Years==="yes",
  en:{q:"Tell us about those travels.",intro:"Where did you go, when, and why?",ph:"e.g. Colombia, March 2022, visited my sister / Mexico, June 2021, business conference…"},
  es:{q:"Cuéntanos sobre esos viajes.",intro:"¿Dónde fuiste, cuándo y por qué?",ph:"ej. Colombia, marzo 2022, visita a mi hermana / México, junio 2021, conferencia de negocios…"},
  fr:{q:"Parlez-nous de ces voyages.",intro:"Où êtes-vous allé(e), quand et pourquoi?",ph:"ex. Colombie, mars 2022, visite à ma sœur / Mexique, juin 2021, conférence…"},
},

// PHASE 5
{id:"countriesAtRisk",phase:5,field:"countriesAtRisk",type:"textarea",
  en:{q:"In which country or countries would you be at risk?",intro:"Usually your home country. But include any other country where you have citizenship or lived and would also face risk there.",ph:"List all countries where you would face persecution, torture, or risk to your life…"},
  es:{q:"¿En qué país o países estarías en riesgo?",intro:"Normalmente tu país de origen. Pero incluye cualquier otro país donde tengas ciudadanía o hayas vivido y donde también enfrentarías riesgos.",ph:"Lista todos los países donde enfrentarías persecución, tortura o riesgo para tu vida…"},
  fr:{q:"Dans quel(s) pays seriez-vous en danger?",intro:"Généralement votre pays d'origine. Mais incluez tout autre pays dont vous avez la citoyenneté ou où vous avez vécu et où vous feriez face à des risques.",ph:"Listez tous les pays où vous seriez confronté(e) à des persécutions, à la torture ou à un risque pour votre vie…"},
},
{id:"wantedByAuthorities",phase:5,field:"wantedByAuthorities",type:"choice",
  en:{q:"Are you — or were you — wanted by the police, military, or any government authorities in any country?",intro:"Being wanted by authorities is different from having a criminal record. Many PRRA applicants are wanted because they spoke out, due to their religion, or ethnicity — not because they did anything wrong."},
  es:{q:"¿Eres — o eras — buscado/a por la policía, el ejército, o alguna autoridad gubernamental en algún país?",intro:"Ser buscado/a es diferente a tener antecedentes. Muchos solicitantes son buscados por hablar contra el gobierno, por su religión o etnia."},
  fr:{q:"Êtes-vous — ou étiez-vous — recherché(e) par la police, l'armée ou des autorités dans un pays?",intro:"Être recherché(e) est différent d'avoir un casier. Beaucoup de demandeurs sont recherchés parce qu'ils ont parlé contre le gouvernement."},
  opts:[
    {v:"yes",e:"⚠️",en:"Yes — I am or was wanted by authorities",   es:"Sí — soy o fui buscado/a por autoridades",  fr:"Oui — je suis ou j'ai été recherché(e) par des autorités"},
    {v:"no", e:"✅",en:"No — I am not wanted by any authority",     es:"No — no soy buscado/a por ninguna autoridad",fr:"Non — je ne suis pas recherché(e) par une autorité"},
  ],
},
{id:"wantedCountries",phase:5,field:"wantedCountries",type:"text",when:a=>a.wantedByAuthorities==="yes",
  en:{q:"In which countries are you or were you wanted?",ph:"List all countries where you are or were wanted by authorities"},
  es:{q:"¿En qué países eres o eras buscado/a?",ph:"Lista todos los países donde eres o eras buscado/a por las autoridades"},
  fr:{q:"Dans quels pays êtes-vous ou étiez-vous recherché(e)?",ph:"Listez tous les pays où vous êtes ou étiez recherché(e) par les autorités"},
},
{id:"prevRefugeeClaims",phase:5,field:"prevRefugeeClaims",type:"choice",
  en:{q:"Have you ever applied for refugee protection — at a Canadian visa office abroad, or in Canada?",intro:"This is separate from the PRRA you are applying for now. Have you EVER made a formal refugee application before?"},
  es:{q:"¿Alguna vez has solicitado protección como refugiado/a — en una oficina de visas canadiense en el extranjero, o en Canadá?",intro:"Esto es separado del PRRA que estás solicitando ahora."},
  fr:{q:"Avez-vous déjà demandé la protection des réfugiés — dans un bureau des visas canadien à l'étranger ou au Canada?",intro:"C'est distinct du PRRA que vous demandez maintenant."},
  opts:[
    {v:"abroad", e:"🌍",en:"Yes — at a Canadian visa office in another country",  es:"Sí — en una oficina de visas canadiense en otro país",  fr:"Oui — dans un bureau des visas canadien dans un autre pays"},
    {v:"canada", e:"🍁",en:"Yes — for refugee protection in Canada",               es:"Sí — para protección como refugiado/a en Canadá",       fr:"Oui — pour la protection des réfugiés au Canada"},
    {v:"both",   e:"🌍",en:"Yes — both abroad and in Canada",                      es:"Sí — tanto en el extranjero como en Canadá",           fr:"Oui — à la fois à l'étranger et au Canada"},
    {v:"no",     e:"❌",en:"No — I have never made a refugee claim",               es:"No — nunca hice una solicitud de refugio",             fr:"Non — je n'ai jamais fait de demande d'asile"},
  ],
},
{id:"prevClaimsDetails",phase:5,field:"prevClaimsDetails",type:"repeat",
  when:a=>["abroad","canada","both"].includes(a.prevRefugeeClaims),
  max:2,
  en:{q:"Tell us about those previous refugee claims.",addBtn:"Add a claim",doneBtn:"I have added all previous claims"},
  es:{q:"Cuéntanos sobre esas solicitudes de refugio anteriores.",addBtn:"Agregar una solicitud",doneBtn:"Ya agregué todas las solicitudes anteriores"},
  fr:{q:"Parlez-nous de ces demandes d'asile précédentes.",addBtn:"Ajouter une demande",doneBtn:"J'ai ajouté toutes les demandes précédentes"},
  subFields:[
    {id:"claimCountry",req:true,en:{label:"Claim made in (country)",ph:"e.g. Canada"},es:{label:"Solicitud hecha en (país)"},fr:{label:"Demande faite en (pays)"}},
    {id:"fleeingFrom", req:true,en:{label:"Fleeing from (country)"},                 es:{label:"Huyendo de (país)"},         fr:{label:"Fuyant (pays)"}},
    {id:"claimDate",   req:true,en:{label:"Date of claim",ph:"e.g. 05/2022"},        es:{label:"Fecha de la solicitud"},     fr:{label:"Date de la demande"}},
    {id:"result",      req:true,en:{label:"Result",ph:"e.g. Rejected, Pending, Withdrawn, Accepted"},es:{label:"Resultado"},fr:{label:"Résultat"}},
    {id:"leftCanada",       en:{label:"If in Canada — date you left Canada (if applicable)",ph:"e.g. 08/2023 or N/A"},es:{label:"Si fue en Canadá — fecha en que saliste"},fr:{label:"Si au Canada — date à laquelle vous avez quitté le Canada"}},
  ],
},
{id:"conventionRefugeeOther",phase:5,field:"conventionRefugeeOther",type:"choice",
  en:{q:"Have you ever asked to be recognized as a Convention refugee in any country other than Canada?",intro:"This is a formal refugee claim in another country like the USA, Germany, France, etc. — under the 1951 Refugee Convention."},
  es:{q:"¿Alguna vez pediste ser reconocido/a como refugiado/a de la Convención en algún país que no sea Canadá?",intro:"Esto es una solicitud formal de refugio en otro país como EE.UU., Alemania, Francia, etc."},
  fr:{q:"Avez-vous déjà demandé à être reconnu(e) comme réfugié(e) au sens de la Convention dans un pays autre que le Canada?",intro:"Il s'agit d'une demande formelle dans un autre pays comme les États-Unis, l'Allemagne, la France, etc."},
  opts:[
    {v:"yes",e:"✅",en:"Yes — I made such a claim in another country",es:"Sí — hice tal solicitud en otro país",          fr:"Oui — j'ai fait une telle demande dans un autre pays"},
    {v:"no", e:"❌",en:"No — I have never done this",                 es:"No — nunca lo hice",                           fr:"Non — je ne l'ai jamais fait"},
  ],
},
{id:"conventionClaimsDetails",phase:5,field:"conventionClaimsDetails",type:"repeat",when:a=>a.conventionRefugeeOther==="yes",
  max:3,
  en:{q:"Tell us about those Convention refugee claims in other countries.",addBtn:"Add a claim",doneBtn:"I have added all claims"},
  es:{q:"Cuéntanos sobre esas solicitudes de refugio en otros países.",addBtn:"Agregar una solicitud",doneBtn:"Ya agregué todas"},
  fr:{q:"Parlez-nous de ces demandes de réfugié dans d'autres pays.",addBtn:"Ajouter une demande",doneBtn:"J'ai ajouté toutes"},
  subFields:[
    {id:"claimCountry",req:true,en:{label:"Claim made in (country)"},es:{label:"Solicitud hecha en (país)"},fr:{label:"Demande faite en (pays)"}},
    {id:"fleeingFrom", req:true,en:{label:"Fleeing from (country)"},es:{label:"Huyendo de (país)"},fr:{label:"Fuyant (pays)"}},
    {id:"claimDate",   req:true,en:{label:"Date of claim",ph:"e.g. 06/2021"},es:{label:"Fecha de la solicitud"},fr:{label:"Date de la demande"}},
    {id:"result",      req:true,en:{label:"Result",ph:"e.g. Recognized as refugee, Rejected, Pending"},es:{label:"Resultado"},fr:{label:"Résultat"}},
    {id:"docIssued",       en:{label:"If a document was issued: date and serial number",ph:"e.g. 08/2021, #RF1234"},es:{label:"Si se emitió documento: fecha y número de serie"},fr:{label:"Si un document a été délivré: date et numéro de série"}},
  ],
},
{id:"unhcrApplication",phase:5,field:"unhcrApplication",type:"choice",
  en:{q:"Have you ever applied for refugee status with the United Nations (UNHCR)?",intro:"The UNHCR is the UN agency that helps refugees in many countries around the world."},
  es:{q:"¿Alguna vez has solicitado el estatus de refugiado ante las Naciones Unidas (ACNUR)?",intro:"El ACNUR es la agencia de la ONU que ayuda a los refugiados en muchos países del mundo."},
  fr:{q:"Avez-vous déjà demandé le statut de réfugié auprès des Nations Unies (UNHCR)?",intro:"Le HCR est l'agence de l'ONU qui aide les réfugiés dans de nombreux pays."},
  opts:[
    {v:"yes",e:"✅",en:"Yes — I applied to the UNHCR",            es:"Sí — solicité al ACNUR",          fr:"Oui — j'ai demandé au HCR"},
    {v:"no", e:"❌",en:"No — I have never applied to the UNHCR",  es:"No — nunca solicité al ACNUR",    fr:"Non — je n'ai jamais demandé au HCR"},
  ],
},
{id:"unhcrNoExplain",phase:5,field:"unhcrNoExplain",type:"textarea",when:a=>a.unhcrApplication==="no",
  en:{q:"Please explain why you did not apply to the UNHCR.",intro:"Common reasons: the UNHCR was not present in your country, you did not know about them, or it was not safe to approach any official body.",ph:"e.g. The UNHCR does not operate in my country / I was not aware of this option / It was too dangerous to approach any official body…"},
  es:{q:"Por favor explica por qué no solicitaste al ACNUR.",ph:"ej. El ACNUR no opera en mi país / No sabía sobre esta opción / Era demasiado peligroso acercarme a cualquier organismo oficial…"},
  fr:{q:"Veuillez expliquer pourquoi vous n'avez pas demandé au HCR.",ph:"ex. Le HCR n'opère pas dans mon pays / Je n'étais pas au courant / Il était trop dangereux d'approcher un organisme officiel…"},
},
{id:"unhcrYesDetails",phase:5,field:"unhcrYesDetails",type:"grouped",when:a=>a.unhcrApplication==="yes",
  en:{q:"Tell us about your UNHCR application."},
  es:{q:"Cuéntanos sobre tu solicitud al ACNUR."},
  fr:{q:"Parlez-nous de votre demande au HCR."},
  subFields:[
    {id:"country",    req:true,en:{label:"Country where you applied to the UNHCR"},                                                                            es:{label:"País donde solicitaste al ACNUR"},                                           fr:{label:"Pays où vous avez demandé au HCR"}},
    {id:"recognized", req:true,en:{label:"Were you recognized as a Convention refugee?"},es:{label:"¿Fuiste reconocido/a como refugiado/a?"},fr:{label:"Avez-vous été reconnu(e) comme réfugié(e)?"},type:"select",opts:[{v:"yes",en:"Yes",es:"Sí",fr:"Oui"},{v:"no",en:"No",es:"No",fr:"Non"},{v:"pending",en:"Pending",es:"Pendiente",fr:"En attente"}]},
    {id:"hasDoc",      req:true,en:{label:"Do you have a document confirming your UNHCR status?"},es:{label:"¿Tienes un documento que confirme tu estatus?"},fr:{label:"Avez-vous un document confirmant votre statut?"},type:"select",opts:[{v:"yes",en:"Yes — I have it and will include a copy",es:"Sí — lo tengo e incluiré una copia",fr:"Oui — je l'ai et joindrai une copie"},{v:"no",en:"No",es:"No",fr:"Non"}]},
  ],
},
{id:"familyClaimsInCanada",phase:5,field:"familyClaimsInCanada",type:"repeat",
  max:3,
  en:{q:"Do any of your family members or relatives have their own refugee claim or PRRA in Canada?",intro:"This is about family with their OWN separate history — not people applying together with you now.",addBtn:"Add a family member with a claim in Canada",doneBtn:"I have added all family claims",skipBtn:"No — none of my family has a separate claim in Canada"},
  es:{q:"¿Alguno de tus familiares tiene su propia solicitud de refugio o PRRA en Canadá?",intro:"Esto es sobre familiares con su PROPIO historial separado — no las personas que aplican contigo ahora.",addBtn:"Agregar un familiar con solicitud en Canadá",doneBtn:"Ya agregué todas las solicitudes familiares",skipBtn:"No — ningún familiar tiene solicitud separada en Canadá"},
  fr:{q:"Certains membres de votre famille ont-ils leur propre demande d'asile ou PRRA au Canada?",intro:"Il s'agit de membres de la famille avec leur PROPRE historique séparé.",addBtn:"Ajouter un proche avec une demande au Canada",doneBtn:"J'ai ajouté toutes les demandes familiales",skipBtn:"Non — aucun proche n'a de demande séparée au Canada"},
  subFields:[
    {id:"fullName",    req:true,en:{label:"Full name"},es:{label:"Nombre completo"},fr:{label:"Nom complet"}},
    {id:"relationship",req:true,en:{label:"Relationship to you",ph:"e.g. Brother, Mother, Cousin"},es:{label:"Relación contigo"},fr:{label:"Lien de parenté"}},
    {id:"claimDate",   req:true,en:{label:"Date of claim",ph:"e.g. 04/2023"},es:{label:"Fecha de la solicitud"},fr:{label:"Date de la demande"}},
    {id:"claimCountry",req:true,en:{label:"Claim made in (country)"},es:{label:"Solicitud hecha en"},fr:{label:"Demande faite en"}},
    {id:"fleeingFrom", req:true,en:{label:"Fleeing from (country)"},es:{label:"Huyendo de (país)"},fr:{label:"Fuyant (pays)"}},
    {id:"result",           en:{label:"Result (if known)",ph:"e.g. Approved, Rejected, Pending"},es:{label:"Resultado (si se conoce)"},fr:{label:"Résultat (si connu)"}},
  ],
},

// PHASE 6
{id:"storyDanger",phase:6,field:"storyDanger",type:"story",claudeQ:"why_danger",
  en:{q:"Tell us your story — why would you be in danger if you had to return to your country?",intro:"This is the most important part of your application. Take your time. Write in any language — our system will process it. The more details you share, the stronger your case. Nothing you say here is wrong.",ph:"Tell us what happened to you. For example: I received death threats because… / I was arrested because of my… / My family was attacked by… / I am targeted because I am…"},
  es:{q:"Cuéntanos tu historia — ¿por qué estarías en peligro si tuvieras que regresar a tu país?",intro:"Esta es la parte más importante. Tómate tu tiempo. Puedes escribir en cualquier idioma. Cuantos más detalles compartas, más sólido será tu caso.",ph:"Cuéntanos qué te pasó. Por ejemplo: Recibí amenazas de muerte porque… / Me arrestaron por mi… / Mi familia fue atacada por… / Soy perseguido/a porque…"},
  fr:{q:"Racontez votre histoire — pourquoi seriez-vous en danger si vous deviez retourner dans votre pays?",intro:"C'est la partie la plus importante. Prenez votre temps. Écrivez dans n'importe quelle langue. Plus vous partagez de détails, plus votre dossier sera solide.",ph:"Racontez ce qui vous est arrivé. Par exemple: J'ai reçu des menaces de mort parce que… / J'ai été arrêté(e) à cause de mon… / Ma famille a été attaquée par…"},
},
{id:"storyRiskType",phase:6,field:"storyRiskType",type:"story",claudeQ:"risk_type",
  en:{q:"What exactly could happen to you if you returned? Describe the danger in detail.",intro:"Tell us specifically what you fear. The more concrete and personal you are, the stronger your case.",ph:"e.g. I would be arrested and tortured by… / I would be killed by… / I would be persecuted because of my religion / political opinion / ethnicity / membership in a group…"},
  es:{q:"¿Qué exactamente podría pasarte si regresaras? Describe el peligro con detalle.",ph:"ej. Sería arrestado/a y torturado/a por… / Sería asesinado/a por… / Sería perseguido/a por mi religión / opinión política / etnia…"},
  fr:{q:"Que pourrait-il exactement vous arriver si vous retourniez? Décrivez le danger en détail.",ph:"ex. Je serais arrêté(e) et torturé(e) par… / Je serais tué(e) par… / Je serais persécuté(e) en raison de ma religion / opinion politique / appartenance à un groupe…"},
},
{id:"storyPersonal",phase:6,field:"storyPersonal",type:"story",claudeQ:"personal_risk",
  en:{q:"Why is it YOU specifically who is in danger?",intro:"A judge needs to see that YOU personally are targeted — not just that your country is difficult for everyone. Tell us about specific threats you received or incidents that happened to you.",ph:"e.g. I personally received a death threat letter signed by… / I was specifically named in a list of people to be arrested / I am personally identified as a target because…"},
  es:{q:"¿Por qué TÚTÚ específicamente estás en peligro?",intro:"Un juez necesita ver que TÚ personalmente eres el objetivo — no solo que tu país sea difícil para todos.",ph:"ej. Yo personalmente recibí una carta de amenaza firmada por… / Fui nombrado/a específicamente en una lista…"},
  fr:{q:"Pourquoi est-ce VOUS spécifiquement qui êtes en danger?",intro:"Un juge doit voir que VOUS personnellement êtes ciblé(e) — pas seulement que votre pays est difficile pour tout le monde.",ph:"ex. J'ai personnellement reçu une lettre de menace signée par… / J'ai été spécifiquement nommé(e) dans une liste…"},
},
{id:"storyInternal",phase:6,field:"storyInternal",type:"story",claudeQ:"internal_flight",
  en:{q:"Could you escape the danger by moving to a different city or region in your country?",intro:"Judges always ask this. If the answer is no, explain why the danger would follow you everywhere.",ph:"e.g. The government or group threatening me operates everywhere in the country / I tried to move to [city] but they found me / There is no safe place for me because…"},
  es:{q:"¿Podrías escapar del peligro mudándote a otra ciudad o región de tu país?",ph:"ej. El gobierno o grupo que me amenaza opera en todo el país / Intenté mudarme a [ciudad] pero me encontraron / No hay lugar seguro para mí porque…"},
  fr:{q:"Pourriez-vous échapper au danger en déménageant dans une autre ville ou région de votre pays?",ph:"ex. Le gouvernement ou le groupe qui me menace opère dans tout le pays / J'ai essayé de déménager à [ville] mais ils m'ont retrouvé(e)…"},
},
{id:"storyGeneral",phase:6,field:"storyGeneral",type:"story",claudeQ:"general_risk",
  en:{q:"How is your situation different from what most ordinary people in your country experience every day?",intro:"The law requires showing that your risk is personal and specific — not something that affects everyone equally.",ph:"e.g. Most people in my country do not face this specific threat. I face it because I am a journalist / activist / LGBTQ+ person / political opponent / religious minority member / member of a specific group…"},
  es:{q:"¿Cómo es tu situación diferente a lo que viven la mayoría de las personas ordinarias en tu país?",ph:"ej. La mayoría de las personas en mi país no enfrentan esta amenaza específica. Yo la enfrento porque soy un/a periodista / activista / persona LGBTQ+ / opositor político…"},
  fr:{q:"En quoi votre situation est-elle différente de ce que vivent la plupart des gens ordinaires dans votre pays?",ph:"ex. La plupart des gens dans mon pays ne font pas face à cette menace spécifique. J'y suis confronté(e) parce que je suis journaliste / militant(e) / personne LGBTQ+…"},
},
{id:"protectionSought",phase:6,field:"protectionSought",type:"story",claudeQ:"protection_sought",
  en:{q:"Did you try to get protection from the police or government in your country? What happened?",intro:"This is very important. If you went to the police and they refused, ignored you, or were the ones threatening you — that is powerful evidence for your case. If you did not go to the police, explain why.",ph:"e.g. I went to the police and they told me they could not help because… / I filed a complaint but nothing happened / I did not go to the police because they were working with the people threatening me / Going to the police would have put me in more danger because…"},
  es:{q:"¿Intentaste obtener protección de la policía o del gobierno de tu país? ¿Qué pasó?",intro:"Esto es muy importante. Si fuiste a la policía y se negaron a ayudarte, te ignoraron, o ellos eran quienes te amenazaban — esa es evidencia poderosa para tu caso.",ph:"ej. Fui a la policía y me dijeron que no podían ayudarme porque… / Presenté una denuncia pero no pasó nada / No fui a la policía porque trabajaban con quienes me amenazaban…"},
  fr:{q:"Avez-vous essayé d'obtenir la protection de la police ou du gouvernement dans votre pays? Que s'est-il passé?",intro:"C'est très important. Si vous êtes allé(e) à la police et qu'elle a refusé, vous a ignoré(e), ou était celle qui vous menaçait — c'est une preuve puissante pour votre dossier.",ph:"ex. Je suis allé(e) à la police et on m'a dit qu'elle ne pouvait pas m'aider parce que… / J'ai déposé une plainte mais rien ne s'est passé…"},
},

// PHASE 7
{id:"documents",phase:7,field:"documents",type:"multiChoice",
  en:{q:"Which supporting documents do you have?",intro:"Supporting documents strengthen your case significantly. Check everything you have. Do not worry if you are missing some — they will still be listed."},
  es:{q:"¿Qué documentos de apoyo tienes?",intro:"Los documentos de apoyo fortalecen significativamente tu caso. Marca todo lo que tengas."},
  fr:{q:"Quels documents de soutien avez-vous?",intro:"Les documents de soutien renforcent considérablement votre dossier. Cochez tout ce que vous avez."},
  opts:[
    {v:"passport",  e:"🪪",en:"Passport or national ID card",                  es:"Pasaporte o cédula de identidad",           fr:"Passeport ou carte d'identité nationale"},
    {v:"threats",   e:"✉️",en:"Threatening letters, emails, or messages",      es:"Cartas, correos o mensajes amenazantes",    fr:"Lettres, emails ou messages de menace"},
    {v:"police",    e:"📋",en:"Police reports or court documents",              es:"Reportes policiales o documentos judiciales",fr:"Rapports de police ou documents judiciaires"},
    {v:"medical",   e:"🏥",en:"Medical records showing injuries or trauma",    es:"Expedientes médicos de lesiones o trauma",  fr:"Dossiers médicaux montrant des blessures ou un traumatisme"},
    {v:"news",      e:"📰",en:"News articles about my situation or country",   es:"Artículos de noticias sobre mi situación", fr:"Articles de presse sur ma situation ou mon pays"},
    {v:"photos",    e:"📷",en:"Photos or videos as evidence",                  es:"Fotos o videos como evidencia",            fr:"Photos ou vidéos comme preuves"},
    {v:"witness",   e:"👁️",en:"Written statements from witnesses",            es:"Declaraciones escritas de testigos",        fr:"Déclarations écrites de témoins"},
    {v:"org",       e:"🏢",en:"Letters from organizations or NGOs",            es:"Cartas de organizaciones o ONGs",          fr:"Lettres d'organisations ou d'ONG"},
    {v:"other",     e:"📁",en:"Other supporting documents",                    es:"Otros documentos de apoyo",                fr:"Autres documents de soutien"},
  ],
  noneOpt:{en:"I do not have any supporting documents yet",es:"Aún no tengo documentos de apoyo",fr:"Je n'ai pas encore de documents de soutien"},
},
{id:"hasRep",phase:7,field:"hasRep",type:"choice",
  en:{q:"Does anyone act as your representative for this application?",intro:"A representative helps you with the process — a lawyer, consultant, trusted friend, or community worker. You do not need one. But if someone is helping you, we need their details for the official forms."},
  es:{q:"¿Alguien actúa como tu representante para esta solicitud?",intro:"Un representante te ayuda con el proceso — abogado, consultor, amigo de confianza o trabajador comunitario. No es obligatorio. Pero si alguien te ayuda, necesitamos sus datos."},
  fr:{q:"Quelqu'un agit-il comme votre représentant pour cette demande?",intro:"Un représentant vous aide dans le processus — avocat, consultant, ami de confiance ou travailleur communautaire. Ce n'est pas obligatoire. Mais si quelqu'un vous aide, nous avons besoin de ses coordonnées."},
  opts:[
    {v:"no", e:"🙋",en:"No — I am on my own",          es:"No — voy por mi cuenta",          fr:"Non — je me débrouille seul(e)"},
    {v:"yes",e:"👤",en:"Yes — someone is helping me",  es:"Sí — alguien me está ayudando",  fr:"Oui — quelqu'un m'aide"},
  ],
},
{id:"repType",phase:7,field:"repType",type:"choice",when:a=>a.hasRep==="yes",
  en:{q:"What type of representative is it?"},
  es:{q:"¿Qué tipo de representante tiene?"},
  fr:{q:"Quel type de représentant est-ce?"},
  opts:[
    {v:"unpaid",e:"🤝",en:"Unpaid — friend, family, or community volunteer",      es:"No pagado — amigo/a, familiar o voluntario",                fr:"Non rémunéré — ami(e), famille ou bénévole"},
    {v:"cicc",  e:"🏛️",en:"Paid — CICC registered immigration consultant",       es:"Pagado — consultor de inmigración registrado en el CICC",  fr:"Rémunéré — consultant en immigration enregistré au CICC"},
    {v:"lawyer",e:"⚖️",en:"Paid — Lawyer or law society member",                  es:"Pagado — Abogado/a o miembro del colegio de abogados",     fr:"Rémunéré — Avocat(e) ou membre d'un barreau"},
    {v:"notary",e:"📜",en:"Paid — Quebec notary",                                 es:"Pagado — Notario de Quebec",                               fr:"Rémunéré — Notaire du Québec"},
  ],
},
{id:"repName",phase:7,field:"repName",type:"text",when:a=>a.hasRep==="yes",
  en:{q:"What is your representative's full name?",ph:"First name then last name"},
  es:{q:"¿Cuál es el nombre completo de tu representante?",ph:"Nombre y después apellido"},
  fr:{q:"Quel est le nom complet de votre représentant?",ph:"Prénom puis nom de famille"},
},
{id:"repMemberId",phase:7,field:"repMemberId",type:"textSkip",when:a=>a.hasRep==="yes",
  en:{q:"What is their membership or registration ID number?",intro:"Only paid representatives have a membership ID. If unpaid, tap Skip.",ph:"Membership ID — or skip"},
  es:{q:"¿Cuál es su número de membresía o registro?",intro:"Solo los representantes pagados tienen ID de membresía. Si no es pagado, toca Saltar.",ph:"ID de membresía — o saltar"},
  fr:{q:"Quel est leur numéro d'identifiant d'adhésion?",intro:"Seuls les représentants rémunérés ont un identifiant. Si non rémunéré, appuyez sur Ignorer.",ph:"Identifiant d'adhésion — ou ignorer"},
},
{id:"repOrg",phase:7,field:"repOrg",type:"textSkip",when:a=>a.hasRep==="yes",
  en:{q:"What firm or organization do they work for?",ph:"Firm or organization name — or skip if independent"},
  es:{q:"¿Para qué firma u organización trabaja?",ph:"Nombre de la firma u organización — o saltar"},
  fr:{q:"Pour quel cabinet ou organisation travaillent-ils?",ph:"Nom du cabinet ou de l'organisation — ou ignorer"},
},
{id:"repPhone",phase:7,field:"repPhone",type:"text",when:a=>a.hasRep==="yes",
  en:{q:"What is your representative's phone number?",ph:"Phone number with area code"},
  es:{q:"¿Cuál es el número de teléfono de tu representante?",ph:"Número de teléfono con código de área"},
  fr:{q:"Quel est le numéro de téléphone de votre représentant?",ph:"Numéro de téléphone avec indicatif régional"},
},
{id:"repEmail",phase:7,field:"repEmail",type:"text",when:a=>a.hasRep==="yes",
  en:{q:"What is your representative's email address?",ph:"Email address"},
  es:{q:"¿Cuál es la dirección de correo de tu representante?",ph:"Dirección de correo electrónico"},
  fr:{q:"Quelle est l'adresse courriel de votre représentant?",ph:"Adresse courriel"},
},
{id:"repAddress",phase:7,field:"repAddress",type:"text",when:a=>a.hasRep==="yes",
  en:{q:"What is your representative's complete address?",ph:"Street, city, province, postal code"},
  es:{q:"¿Cuál es la dirección completa de tu representante?",ph:"Calle, ciudad, provincia, código postal"},
  fr:{q:"Quelle est l'adresse complète de votre représentant?",ph:"Rue, ville, province, code postal"},
},
{id:"review",phase:7,field:null,type:"review",
  en:{q:"Let us review everything before we prepare your documents."},
  es:{q:"Revisemos todo antes de preparar tus documentos."},
  fr:{q:"Examinons tout avant de préparer vos documents."},
},
];

export const getActiveSteps = (answers) =>
  STEPS.filter(s => !s.when || s.when(answers));
